theme: jekyll-theme-cayman
title: Computational methods and their applications on single cell multiomic data
description: "held in conjunction with IEEE BIBM 2021 \n Houston, TX, USA"
github:
  is_project_page: false
